### ISSUE TITLE
Descriptrion on hub.docker.com

### ISSUE THREAD

**Issue by sklukin** [jhthorsen/app-mojopaste#13]
Hi!
Edit description for https://hub.docker.com/r/jhthorsen/mojopaste/

I think like this

* mkdir /some/dir/fordata
* docker run -d --restart always --name mojopaste -v /some/dir/fordata:/app/data -p 5555:8080 jhthorsen/mojopaste
* go to http://localhost:5555

I test this. Its work

**Comment by jhthorsen** [comment]
Let me know if you have anything that you think should be changed.

**Comment by sklukin** [comment]
If it is not difficult for you, then change the description about run also here - https://hub.docker.com/r/jhthorsen/mojopaste/

Some people can find it on hub.docker.com

**Comment by jhthorsen** [comment]
It's automatically updated from the README.md file. Maybe you checked it too early..?

**Comment by sklukin** [comment]
Оu. I thought it was done by hand. on hub.docker.com. Cool. Ee. Now its correct description. Thanks.

**Comment by jhthorsen** [comment]
It's pretty cool: Every push to "master" branch will cause a new build at hub.docker.com, which also updates the description from README.md.
