### ISSUE TITLE
No pass reports with 1.01 and later

### ISSUE THREAD

**Issue by eserte** [jhthorsen/app-mojopaste#19]
The test suite fails on all of my smokers (and also on other systems) for 1.01, 1.02, and 1.03:
http://matrix.cpantesters.org/?dist=App-mojopaste;maxver=1

**Comment by jhthorsen** [comment]
That is quite embarrassing! I simple forgot to run the old tests when I released the new version.

v1.04 Should be available for testing soon. Hope that helps.
